### ISSUE TITLE
Sentora Website Probelm

### ISSUE THREAD

**Issue by shabbirhasan** [sentora/sentora-installers#133]
I have a install sentora but website not working. please check

**Comment by bradjtrammell** [comment]
You have not included any information on your situation. At an absolute minimum we need to know:

- Your servers operating system (CentOS, Debian, Ubuntu, etc) and version number
- Whether you used the official Sentora installer (found on the Sentora website)
- Specifics about your situation, what are you expecting that hasn't happened
- Any error messages you're experiencing
- And lastly, what your expected results are.

It is best do make these types of requests on the actual Sentora forums (forums.sentora.org) so that your request will be seen, and answered in a timely manner. Lets start with what you have above and most likely we can fix your issue.

**Comment by Dukecitysolutions** [comment]
Closing. User did not respond
