### ISSUE TITLE
Ubuntu file questions.

### ISSUE THREAD

**Issue by PS2Guy** [sentora/sentora-installers#25]
When installing on Ubuntu, the installer installs new bind9 e.t.c files, the OS asks what we want to do with these files.

This may prove confusing to NOOBS.

**Comment by dannystyleart** [comment]
Hello guys,

I was installed third time sentora on my digitalOcean vps (x64 ubuntu 14.04 LTS). I have stuck on configuring thunderbird on the freshly created mailbox. The mail is working well I could send emails from and to the address.

Did you faced with this?

**Comment by Ron-e** [comment]
@dannystyleart isn't that question more a thing for on the forum?
http://forums.sentora.org/

**Comment by dannystyleart** [comment]
Well in the last 2days I could not open the forum. Btw as I'm searching in the term of smpt pop3 client it throws only threads of sending issues but no client setup.
I'll register and we'll se. Thanks for your reply

**Comment by 5050** [comment]
@dannystyleart : 
Your question have nothing related to the problem reported by ps2guy.  Please open a new subject in the forums. I did not noticed any break in the forum access since many month. Did you really tryed http://forums.sentora.org ?

I will remove the lasts 3 posts to leave the subject understandable. 

For info : PS2Guy was using a VPS from Crissic and gave me an access on one. After spending long time trying to adapt the installer, I leaved : they are using a highly modified Ubuntu version to light as much as possible the load of their servers : cron tasks are all disabled, many packages are removed or reconfigured, etc.  it is not at all a "standard" minimal Ubuntu server despite the reported name unchanged.
